### PR TITLE
notification handling

### PR DESCRIPTION
**Pull request by reka**
There was a change in ResponseMapper according to [the sample notification](https://document-center.wirecard.com/display/PTD/Debit+for+paypal)
The expected statuses collection does not look like this:
```
self::STATUSES => [
                    [
                        self::STATUS_CODE => '200',
                        self::STATUS_DESCRIPTION => 'UnitTest',
                        self::STATUS_SEVERITY => 'warning'
                    ],
                    [
                        self::STATUS_CODE => '500',
                        self::STATUS_DESCRIPTION => 'UnitTest Error',
                        self::STATUS_SEVERITY => 'error'
                    ],
                ]
```
But like this:
```
self::STATUSES => [
                    ['status' =>
                        [
                            self::STATUS_CODE => '200',
                            self::STATUS_DESCRIPTION => 'UnitTest',
                            self::STATUS_SEVERITY => 'warning'
                        ]],
                    ['status' =>
                        [
                            self::STATUS_CODE => '500',
                            self::STATUS_DESCRIPTION => 'UnitTest Error',
                            self::STATUS_SEVERITY => 'error'
                        ],
                    ]]
```

Please review whether it's OK this way.

### CODE REVIEW

**Comment by reka** [comment]
open question: Do we have further sample notifications?
Can it happen that a success notification contains more statuses?
If yes, which one contains the relevant provider transaction ID: the first one, the last one?

**Comment by JuEger** [comment]
More than one status should only be present if there are errors. Then there would not be a provider transaction id. What we could to, just to be sure, is iterate over all status entries and take the first occurrence of the provider transaction ID. We should never get 2 different provider transaction IDs in one request.

**Comment by reka** [comment]
Can it happen that the response does not contain a provider transaction ID at all?

**Comment by reka** [comment]
Notification handling will be rewritten using xml responses.

**Pull request closed without merging**
